# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines-ado

pool:
  vmImage: 'windows-2019'

steps:

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: 'dotnetcore-webapp.csproj'
    feedsToUse: 'select'
    vstsFeed: '04026f9a-aa91-4098-980b-fa301d1dbce9/acab9c0c-85c5-466d-b030-93c4eb70da75'


- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: 'dotnetcore-webapp.csproj'


- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    publishWebProjects: true

- task: PublishBuildArtifacts@1
  displayName: 'build artifacts'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'